identifier = 1*ALPHA *( "_" / "-" / ALPHA / DIGIT )
string = DQUOTE *OCTET DQUOTE
number = 1*DIGIT / *DIGIT "." 1*DIGIT
literal = number / string

crlf = *WSP [CR] LF *WSP
sep = WSP / crlf

eval = identifier
eval =/ eval *("." identifier)
eval =/ eval *(":" identifier "(" *sep [expression (1*sep expression)] *sep ")")

expression = literal / eval

operator = "=" / "!=" / ">" / "<" / ">=" / "<="
condition = expression [*sep operator *sep expression]
condition =/ condition 1*sep "or" 1*sep condition

block = "do" *(crlf statement) crlf "end"
filter = "filter" [1*sep string] 1*WSP block

action = identifier [1*WSP expression]

statement = filter / condition / action
