# location of the main database
db = "/var/lib/atmail/data.db"
# directory containing the mails
directory = "/var/lib/atmail/data"
# folder containing domains' config file
domains_folder = "/etc/atmail/domains.d/"

# domain broadcasted
main_domain = "mail.example.org"

[smtp]
# address to listen to (tcp or unix socket)
listen = ":2525"
# group of unix socket (can be a name or a gid)
#socket_group = "mail"
# permission of the socket
#socket_permission = 0o660
# use PROXY V2 Protocol by HAProxy
use_proxy_v2 = false
#allow_insecure_auth = false
# max mail size in KiB
max_mail_size = 16416

[imap]
listen = ":2993"
use_proxy_v2 = false

#[rspamd]
# Address of the rspamd server
#address = "localhost:11332"

[domains."example.org"]
# if you wanna enable support of plus addressing like 'foo+bar@example.org'
plus_subaddressing = true
# if you wanna create an IMAP folder for each subaddress, like 'INBOX/bar' for 'foo+bar@example.org'
create_folder_subaddressing = false

[domains."example.org".admin]
# admin account (used to redirect postmaster@example.org and other security-related mailboxes to the right user)
user = "admin"
# sets the IMAP folder for this account (empty for INBOX)
#folder = "security"
# if you wanna encrypt with PGP
#pgp_pub_key = ""
#pgp_pub_key_file = ""


# If you wanna use ATProto for the auth
#[domains."example.org".atproto]
#pds = "pds.example.org"
#client_id = "mail.example.org"
#client_secret = "my-secret"

# If you wanna allow only specific users, maps them to their password (hashed with bcrypt)
#[domains."example.org".static.users]
#foo.password = "$2y$10$wWJy64n5j4pU2CscdWRq.er5Z2.V31U5Ntz5uTopLy1fMX87GQEDG"
#bar.password = "$2y$10$fZ1tRpz2mfdRfaaTbx723.Gch7tY.f7LIBuZz1of/cLwBGvU39ivG"
# You can specify their PGP public key to encrypt their message
#foo.pgp_pub_key = ""
#bar.pgp_pub_key_file = ""
# If you want to only permit local connection regardless of the password
#baz.local_only = true

# Catch every mail into one address
[domains."example.org".catch_all]
user = "me"
password = "bcrypt here"
#pgp_pub_key = ""
#pgp_pub_key_file = ""
