# address to listen to (tcp or unix)
listen = ":2525"
#listen = "/run/atmail.sock"
# use PROXY V2 Protocol by HAProxy
use_proxy_v2 = false

# location of the main database
db = "/var/lib/atmail/data.db"
# directory containing the mails
directory = "/var/lib/atmail/data"

# domain broadcasted
main_domain = "mail.example.org"
# max mail size in KiB
max_mail_size = 16416

# If you wanna use ATProto for the auth
#[domains."example.org".atproto]
#pds = "pds.example.org"
#client_id = "mail.example.org"
#client_secret = "my-secret"

# If you wanna allow only specific users, maps them to their password (hashed with bcrypt)
#[domains."example.org".static]
#users.foo = "$2y$10$wWJy64n5j4pU2CscdWRq.er5Z2.V31U5Ntz5uTopLy1fMX87GQEDG"
#users.bar = "$2y$10$fZ1tRpz2mfdRfaaTbx723.Gch7tY.f7LIBuZz1of/cLwBGvU39ivG"

# Catch every mail into one address
[domains."example.org".catch_all]
user = "me"
password = "bcrypt here"
